# Оптимизированная конфигурация для 40M абонентов
# Максимальная производительность с учётом ограничений диска

# Параллелизм
workers: 12              # Все доступные ядра CPU
writer_tasks: 6          # workers/2 для оптимального баланса

# Оптимизация памяти
event_pool_size: 50000      # Увеличено в 5x (было 10000) для меньшего wrap-around
batch_size_bytes: 52428800  # 50MB (было 10MB) для лучшего batching и сжатия

# База данных абонентов
db_history_days: 2          # Минимальная история для экономии места
db_device_change_rate: 0.05 # Вероятность смены устройства в год (снижено)
db_number_release_rate: 0.01 # Вероятность освобождения номера в год (снижено)
db_cooldown_days: 30        # Период "остывания" номера

# Генерация событий (стандартные параметры)
avg_calls_per_user: 3.5
avg_sms_per_user: 5.2
avg_data_sessions_per_user: 12.0
