services:
  heaptrack:
    build:
      context: .
      dockerfile: Dockerfile.bytehound
    container_name: rs_cdr_heaptrack
    volumes:
      # Mount test data
      - ./test_db_1m.arrow:/work/test_db_1m.arrow:ro
      - ./test_config.yaml:/work/test_config.yaml:ro
      # Mount output directories
      - ./prof_output:/work/prof_output
    command: /bin/bash -c "tail -f /dev/null"
    # Keep container running for interactive profiling
    stdin_open: true
    tty: true
