# Example configuration file for RS CDR Generator
# Override default settings by providing this file with --config flag

# Population settings
subscribers: 100000
cells: 2000
prefixes:
  - "31612"
  - "31613"
  - "31620"
  - "31621"
mccmnc_pool:
  - "20408"  # KPN Netherlands
  - "20416"  # T-Mobile Netherlands
  - "20420"  # Vodafone Netherlands

# Geographic settings (Amsterdam region)
center_lat: 52.37
center_lon: 4.895
radius_km: 50.0

# Event rates per user per day
avg_calls_per_user: 3.5
avg_sms_per_user: 5.2
avg_data_sessions_per_user: 12.0

# MO/MT distribution
mo_share_call: 0.5   # 50% mobile-originated calls
mo_share_sms: 0.5    # 50% mobile-originated SMS

# Device behavior
imei_daily_change_prob: 0.02  # 2% chance of IMEI change per day

# Call dispositions (weighted probabilities, must sum to 1.0)
call_dispositions:
  ANSWERED: 0.82
  NO ANSWER: 0.12
  BUSY: 0.04
  FAILED: 0.015
  CONGESTION: 0.005

# Call duration quantiles (seconds)
call_duration_quantiles:
  p50: 75    # Median call duration: 75 seconds
  p90: 240   # 90th percentile: 4 minutes
  p99: 600   # 99th percentile: 10 minutes

# Interconnect traffic share (not currently used)
interconnect_share: 0.15

# Temporal patterns - hourly multipliers (24 values, one per hour)
# Higher values = more activity during that hour
diurnal_weekday:
  - 0.3   # 00:00
  - 0.2   # 01:00
  - 0.15  # 02:00
  - 0.1   # 03:00
  - 0.1   # 04:00
  - 0.15  # 05:00
  - 0.3   # 06:00
  - 0.6   # 07:00
  - 1.2   # 08:00
  - 1.4   # 09:00
  - 1.3   # 10:00
  - 1.2   # 11:00
  - 1.1   # 12:00
  - 1.0   # 13:00
  - 1.1   # 14:00
  - 1.2   # 15:00
  - 1.3   # 16:00
  - 1.5   # 17:00
  - 1.6   # 18:00
  - 1.4   # 19:00
  - 1.2   # 20:00
  - 1.0   # 21:00
  - 0.7   # 22:00
  - 0.5   # 23:00

diurnal_weekend:
  - 0.2   # 00:00
  - 0.15  # 01:00
  - 0.1   # 02:00
  - 0.1   # 03:00
  - 0.1   # 04:00
  - 0.1   # 05:00
  - 0.2   # 06:00
  - 0.3   # 07:00
  - 0.5   # 08:00
  - 0.8   # 09:00
  - 1.0   # 10:00
  - 1.2   # 11:00
  - 1.3   # 12:00
  - 1.2   # 13:00
  - 1.1   # 14:00
  - 1.0   # 15:00
  - 1.1   # 16:00
  - 1.3   # 17:00
  - 1.4   # 18:00
  - 1.3   # 19:00
  - 1.2   # 20:00
  - 1.0   # 21:00
  - 0.6   # 22:00
  - 0.4   # 23:00

# Seasonal patterns - monthly multipliers (1-12)
# Higher values = more activity during that month
seasonality:
  1: 0.95   # January
  2: 0.9    # February
  3: 1.0    # March
  4: 1.05   # April
  5: 1.1    # May
  6: 1.15   # June
  7: 1.2    # July (peak summer)
  8: 1.15   # August
  9: 1.05   # September
  10: 1.0   # October
  11: 0.95  # November
  12: 1.0   # December

# Special days - specific date overrides (YYYY-MM-DD -> multiplier)
# Use to simulate holidays, events, etc.
special_days:
  # Examples (uncomment to use):
  # "2025-12-31": 1.5   # New Year's Eve (50% more activity)
  # "2025-12-25": 0.7   # Christmas (30% less activity)
  # "2025-01-01": 0.8   # New Year's Day
  # "2025-07-04": 1.3   # National holiday

# File rotation threshold (bytes)
rotate_bytes: 100000000  # ~100 MB

# Timezone for local time generation
tz_name: "Europe/Amsterdam"

# Number of worker processes (0 = auto-detect CPU count)
workers: 0
